README.md
docs/code-of-conduct.md
docs/contributing.md

- How to contribute section
- Code of conduct section
- Added Kasey to the team listed

docs: Add 'How to Contribute' documentation

---

package-lock.json
package.json

This problem showed up in [sparkbox/sparkle](https://github.com/sparkbox/sparkle), the `engine` in the `package.json` was set for minor and fix versions only, and really need to have a minimal version for `node` and `npm`.

fix: Set engine to a minimum version

---

Dockerfile
composer.lock
package.json
scripts/run.sh

- Fixes #6 
- Updates the linting scripts in `package.json` to use a convention of `lint:<task>`, which allows us to glob for all lint tasks when using `run-p`
- Runs php scripts in a docker container based on the web image build by docker-compose
- This allows running of PHP scripts without having PHP installed locally or dealing with version inconsistencies
- Supports a `CI=true` flag that can be used for CI
- When `CI=true`, php scripts will be run using the local version of PHP
- This is useful in CI environments where docker is not installed
- Adds an `npm run run:php` command to execute arbitrary scripts inside a PHP container.
1. Pull down this branch
1. Rebuild the docker images: `docker-compose build`
1. Install composer dependencies locally using: `npm run run:php composer …

chore: run linting inside of docker

---

.github/workflows/lint.yml

Adds a workflow to run linting on pull requests against `main`.
1. View the workflow run that was triggered by this PR: https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6089213573/job/16521529691
1. Verify that the output contains linting information and that the linting step passed

chore: add workflow to lint pull requests

---

.github/workflows/lint.yml
package-lock.json
package.json
webpack.common.js
webpack.dev.js
webpack.prod.js

This sets the minimum node version to 18 (the current LTS) and updates the linting workflow to match. As part of this, webpack and its dependencies/implementation needed to be updated to newer major versions for compatibility.
Closes #19 
1. Pull down this branch
2. Run `npm ci` with Node.js v18 or higher running on your machine
3. Run `npm run build:dev` and confirm that it works without errors
4. Run `npm run build:prod` and confirm that it works without errors
5. Run other npm scripts that use JS packages (`lint`, `sass`, `copy`, etc.)

chore: update node version

---

.circleci/config.yml
.github/workflows/lint.yml
Dockerfile
composer.json
composer.lock
package.json
src/php/inc/custom-post-types/example-custom-post-type.php
src/php/inc/helpers/generic.php
src/php/inc/metaboxes/example.php
src/php/inc/taxonomies/example-custom-taxonomy.php
src/php/inc/theme-setup.php
src/php/views/index.twig
src/php/views/search.twig

This PR updates the Dockerfile to use php version 8.1 and Wordpress version 6.3. Additionally this PR updates composer.json to use php version 8.1
Closes #16 
1. Pull down this branch
2. Stop and remove any existing containers running sparkpress 
3. Build the Docker containers `docker compose build`
4. Start the containers `npm run start`
5. Confirm that the newly started container is using php version 8.1. `docker exec sparkpress php -v`

chore: update php + wordpress versions

---

wp-config.php

Prevents the need to manually switch the theme in the wp-admin in order to prevent the error `The theme directory "twentytwentythree" does not exist.` when loading the page.
Closes #25

chore: default theme to sparkpress-theme

---

.github/pull-request-template.md

This adds a PR template to make PR descriptions and validation steps more consistent without making the format too rigid. Since this is a starter template, the comments describe linking to external project management tools instead of the GitHub-style method that references the issue number.
Closes #35 
Ironically, this can't be validated until after it is merged, but confirm that the contents of the template work for what we want.

chore: add PR template

---

.github/workflows/release-please.yml

This adds a workflow to run [Release Please](https://github.com/googleapis/release-please) on merges to `main` to create release PRs. The super simple configuration _should_ work for our use case, analyzing conventional commits to determine a new version number, updating a changelog, and tagging releases (tagging may only happen when the release PR is merged, though).
Closes #23
Closes #38 
1. View the test PR, #47, confirming that it makes sensible changes given the codebase (the changelog ignores chore, style, and refactor commits, which is why there's so little in there)
2. View the output from the [GitHub Action run](https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6267438816/job/17020498793), confirming that despite our lack of any existing releases or a …

chore: set up release please action

---

src/php/archive.php
src/php/example-page-template.php
src/php/functions.php
src/php/page.php
src/php/search.php
src/php/single-example.php
src/php/single.php
src/php/views/single-password.twig
wp-configs/.htaccess

This work adds the required logic and templates to support password protected posts and pages. The newly established pattern is to use the `render_with_password_protection` function on any single post page, which will render the `single-password.twig` template if a password is required. For listing pages, a filter was added to set `has_password` to true for non-admin queries.
Closes #48 
4. Add enough varied test posts to validate when they are or aren't being shown in listing pages
5. In the WordPress editor for one or more posts, set the visibility to "Password protected", and publish the post
6. View the post and confirm that you need to enter a password to see the page
7. Do the same for a Page, such as …

feat: support password protected posts

---

.github/workflows/deploy.pantheon.yml

If no WordPress plugins are installed through composer, `wp-content/plugins` does not exist for build. To prevent build from failing, force creation of the folder if it doesn't exist.
1. View failed Pantheon deployment log, dispatched from `main`.
2. https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6318195516
3. Note that it fails due to missing `wp-content/plugins` folder. This folder is created via `composer install`, but only if the composer deps are WordPress plugins. Since we removed the WordPress plugins from `composer.json`, this folder no longer gets created. 
4. View [successful Pantheon deployment log](https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6318462690/job/17157489584), dispatched from this branch. `mkdir -p` will create the …

fix: force create plugin folder on pantheon deploy

---

src/php/inc/helpers/generic.php

The `GOOGLE_API_KEY` example for loading an environment variable could lead to confusion, since a developer could reasonably expect that it was wired up to a tag manager/analytics script, then be surprised that it didn't do anything. This replaces that key with something that's more clearly an example and includes a comment to reinforce that it's an example.
Closes #54
4. Make sure your site still works as expected (the change shouldn't change any behavior)

refactor: use generic environment variable example to avoid confusion

---

docker-compose.yml

This bumps the MySQL version used by `sparkpress_db` to 8.1, which is [compatible with WordPress 6.3](https://make.wordpress.org/hosting/handbook/compatibility/).
Closes #27
3. Stop your running containers (`docker compose down`)
4. You may want to delete your images and volumes, but that may not be necessary
5. Run `docker compose build`
6. Run `npm start`
7. Visit http://localhost:8000 and confirm that the typical WordPress installation works as expected (or your site works as expected if you didn't delete your DB volume)
8. Download this [DB export](https://github.com/sparkbox/sparkpress-wordpress-starter/files/12731454/db-export-2023-09-26T19-55-14_UTC.sql.gz) and put it in a top-level `sql` folder
9. Run `npm run …

chore: bump mysql image version to 8.1

---

.github/workflows/deploy.pantheon.yml

This fixes our deployment workflow, which is missing the step to install plugin dependencies, causing the [build to fail](https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6341504130/job/17225287279).
3. Run `npm ci`
4. Run `npm run plugins:install`
5. Run `npm run build:prod`
6. Confirm that each of these steps ran successfully and compare them to the deployment workflow, which should effectively do the same thing

fix: install plugin dependencies in deployment workflow

---

docs/structure.md
src/php/functions.php
src/php/views/base.twig

This adds extensions to Twig so that they can be used in Twig components.
Also includes a quick fix to adjust a class attribute with incorrect syntax, see screen shot below from `main` branch:
Closes #57 
2. Pull down this branch but check out one commit back to view the test commit showing that extensions are working properly: `git checkout HEAD~1`
4. In your own database, create a post that does have comments allowed and one that does not, or use this db export: 
[twig-extension-test-db-2023-09-28T21-40-37_UTC.sql.gz](https://github.com/sparkbox/sparkpress-wordpress-starter/files/12754603/twig-extension-test-db-2023-09-28T21-40-37_UTC.sql.gz)
5. Navigate to the post with comments turned on, and the one with comments turned off, …

Chore: add twig extensions

---

src/php/index.php
src/php/views/base.twig
src/php/views/header.twig
src/php/views/menu.twig
src/php/views/partials/content-search.twig
src/php/views/partials/content-single.twig
src/php/views/partials/pagination.twig

This fixes a handful of accessibility issues that are not necessarily blockers, but not ideal. That includes:
- Removing improper ARIA roles
- Adding `aria-label` to different `nav` elements to distinguish between them
- Fixing up the accessibility tree
- Updating heading levels so that the home page link is not the `h1` and that we don't skip straight to `h4`
Closes #69 
4. Go through all non-admin pages and run Lighthouse and/or axe DevTools on each page, confirming that there are no automatically detected issues
5. Inspect the accessibility tree and confirm that the document is structured in a way that makes sense and that elements have the roles and accessible names that you would expect

fix: minor accessibility issues

---

Dockerfile

This change deletes the plugins that are automatically included with the WordPress installation. This removes the noise of unused plugins and their alerts about available updates.
Closes #58 
3. Stop your running containers (`docker compose down`)
4. Run `docker compose build`
5. Run `npm start`
6. Navigate to the Plugins page in the WP admin and confirm that only our "Example Blocks" plugin is shown

chore: delete default plugins on install

---

src/php/functions.php
src/php/inc/theme-setup.php
src/php/views/header.twig
src/php/views/menu.twig

Makes some minor fixes to the registration and usage of menus:
- Adds comments to clarify how multiple menus could be used when registering menus and in `menu.twig` template.
- Removes unused items variable from menu include - this wasn't hurting anything, but also wasn't needed because we are getting menu items in a different way in the menu template.
- Changes argument when Timber Menu is instantiated to use correct menu. This also wasn't hurting anything because we [only have one menu so the argument is optional](https://timber.github.io/docs/reference/timber-menu/#__construct), but would become a problem if anyone wanted to add an additional menu to the existing code.
Closes #77 
4. Confirm that this …

fix: update menu usage

---

src/php/functions.php
src/php/inc/theme-widgets.php
src/php/views/base.twig
src/php/views/footer.twig
src/scss/base.scss
src/scss/components/_post-body.scss
src/scss/components/_primary-sidebar.scss
src/scss/elements/_root.scss

Registers an additional sidebar area (`primary_sidebar`) to be used in the `<aside>` that was already built into the `base.twig` template. Adds minimal styling for the sidebar to visually distinguish it from other parts of the page.
Addresses #75 
4. Navigate to localhost:8000, confirm that no widgets appear in the footer or the sidebar initially (if you've already opened widgets before, reset the db)
5. Navigate to wp-admin, then go to Appearance > Widgets. This automatically fills in registered widget areas with default content.
6. Check localhost:8000 again to confirm that the widgets appear on the page and check sidebar styling.
7. Review scss file additions to confirm that they make sense and follow …

feat: support multiple sidebars

---

src/php/views/partials/pagination.twig
src/scss/base.scss
src/scss/components/_pagination.scss

* Adds aria labeling to pagination links
* Removes previously used disabled buttons
* Adds minimal styling typical of pagination
Closes #70 
4. Import the database if you do not have enough posts in your db to paginate:
[multiple-posts-db-2023-10-03T23-19-21_UTC.sql.gz](https://github.com/sparkbox/sparkpress-wordpress-starter/files/12797666/multiple-posts-db-2023-10-03T23-19-21_UTC.sql.gz)
5. Navigate to localhost:8000 and check that pagination appears to be working as intended

chore: improve pagination

---

package.json

This removes the `postserve:dev` script in favor of using the `--abort-on-container-exit` flag.
Closes #12 
3. Run `npm start`, then Ctrl+C to stop the process (it should behave the same as it did before)
4. Run `npm run serve:dev`, then Ctrl+C to stop the process (it should spin down the containers and return you to a new command line)

chore: simplify docker npm scripts

---

.dockerignore
.github/workflows/deploy.docker.yml
Dockerfile
docker-compose.yml

This adds a GitHub Actions workflow that builds a Docker image using the repo's existing Dockerfile
Closes #21 
**Note:** You should also be able to pull/run the image but it's kind of a hassle! You'd need to [authenticate to the container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic). To run it locally I modified the `docker-compose.yml` as seen below and ran `docker-compose up`.
```
web:
image: ghcr.io/sparkbox/sparkpress:latest
```

chore: workflow to upload theme directory artifact

---

.github/dependabot.yml

This sets up dependabot to create update PRs for npm/composer dependencies on a monthly schedule. To make the process of validating updates simple without risking unexpected breaking changes, the updates are grouped by minor/patch version vs. major version updates, by development vs. production dependencies, and by composer vs. npm dependencies.
[Here's a PR](https://github.com/sparkbox/accessible-components/pull/254) for another project for adding a very similar config, and here's an example [dependabot PR](https://github.com/sparkbox/accessible-components/pull/255) that updated all dev dependencies. The open question about this PR's config is whether Composer behaves the same way as npm.
Closes #92 
2. We can't validate what dependabot will do …

chore: configure dependabot for monthly npm/composer update PRs

---

docs/generators.md
generators/pattern.js
package.json

This adds a generator to register reusable patterns for WordPress editors to use. The template accepts metadata to make finding/understanding the pattern easier, and the sample markup provides both an example and instructions for how to get the markup needed for the pattern.
Closes #95
4. Run `npm run generate:pattern` and answer the questions to create a test pattern
5. Confirm that a new file is added in the `src/php/patterns` directory with content corresponding to your answers to the prompts
6. Add or edit a post in the WP admin, and click the button to add a new block, then go to the Patterns tab
7. Confirm that you can find your new test pattern in the categories that you chose (create another pattern …

feat: add generator for reusable patterns

---

.github/workflows/deploy.pantheon.yml

This adds a check to make sure there is something to commit before proceeding with the deployment to Pantheon. If there's nothing to commit, this will exit early with a success status so that changes that don't affect code that gets copied into the Pantheon repo don't get incorrectly considered as "failed" deployments.
Closes #98
2. View a [failed run](https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6589786740/job/17904992657) and confirm that it failed because there was nothing to commit
3. View the [successful run dispatched from this branch](https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6616215864/job/17970039828) and confirm that it succeeds despite there being nothing to commit to Pantheon's repo

fix: exit deployment process early if nothing to commit

---

src/php/views/page.twig
src/php/views/partials/content-single.twig
src/scss/base.scss
src/scss/components/_post-preview.scss

Utilizes the featured image on a WordPress post in the post list (archive page) as a thumbnail and in the post.
Addresses #75 
4. If you have posts with images, keep the database you already have, or add your own, or use the db backup attached below.
5. Navigate to localhost:8000 to check the archive page, check that thumbnails render and that styling seems appropriate.
6. Navigate to a post page that has a thumbnail image and check that image renders there and that styling seems appropriate.
7. Add a post with a featured image and confirm that image appears on archive page and on post page as expected.
8. Add alt text to a featured image if it does not have one already (you can do this in the Post by …

Support featured image

---

README.md
src/php/comments.php
src/php/inc/theme-setup.php
src/php/views/page.twig
src/php/views/partials/comments.twig

The original statement about comments/pingbacks/trackbacks in the issue stated that "The 'Discussion' section with comments/pingbacks shows up for pages and posts, but checking the boxes doesn't change any behavior". After some discussion, we determined that we could try to temporarily remove all menu options for comments, trackbacks, and pingbacks, and possibly address at least comments later. Removing comments altogether (particularly from the default post) proved difficult and didn't seem like a worthwhile pursuit since it was intended to be a temporary solution only, so this work:
- removes pingbacks and trackbacks to the extent possible
- supports the ability to have comments on posts if desired
Closes #75
3. Run `npm …

feat: support comments

---

README.md
src/php/index.php
src/php/views/404.twig
src/php/views/index.twig
src/php/views/layouts/base.twig
src/php/views/page.twig
src/php/views/partials/content-none.twig
src/php/views/search.twig
src/php/views/single-password.twig
src/scss/components/_primary-sidebar.scss

This PR makes some changes to the markup around the content block in order to resolve a bug that prevented the `.obj-width-limiter` class from centering/spacing content on the page appropriately when the sidebar widget is active. It also refactors how `h1` tags are added to the page, in order to push the sidebar below the `h1` for all pages.
Finally, this PR also adds a minor fix to prevent empty `img` tags from showing on the post page if there is no featured image added.
Closes #119 
4. _Without_ widgets activated [^1], view the following pages, they should appear the same as before (on `main`):
* Index page, http://localhost:8000/
* Post, for instance, http://localhost:8000/?p=1
* Page, for instance, …

Fix: Widget formatting

---

Dockerfile

This updates WordPress to version 6.3.2. See the [release notes](https://wordpress.org/documentation/wordpress-version/version-6-3-2/) for details.
3. Stop your development process if it's already running
4. Run `docker compose build`
5. Run `npm start`
6. Visit the WP dashboard and confirm that it shows as running WordPress version 6.3.2
7. Spot check pages for both the public-facing admin sides for any obvious issues

chore: update WordPress to 6.3.2

---

src/php/views/page.twig
src/php/views/partials/content-single.twig

Implements responsive images on posts using `srcset`. `src/php/views/partials/content-single.twig` still exclusively uses the thumbnail (150x150) image.
Addresses #111 
4. Add a post with a featured image and navigate to it.
5. Open the Network tab in the inspector with a smaller screen width (around 300-400px), and reload the page. Note the name/size of the featured image that loads (it may be 300px wide/`medium` or 768px wide/`medium_large`), and slowly increase the size of the page, depending on your browser, you should see it load at least one other image size (1024px wide/`large`) before the browser window gets to 1000px wide. Different browsers seem to load different sized images and different widths …

feat: add srcset for post image

---

.github/workflows/deploy.docker.yml

Updates the docker workflow to use the auto-generated `GITHUB_TOKEN` instead of one that we set.
2. View the successful [deployment workflow run](https://github.com/sparkbox/sparkpress-wordpress-starter/actions/runs/6710184272), dispatched from this branch
3. View the [latest Docker image](https://github.com/sparkbox/sparkpress-wordpress-starter/pkgs/container/sparkpress/142982627?tag=latest) that was pushed by the above workflow

chore: use GITHUB_TOKEN in docker build

---

.eslintrc
generators/custom-block.js
package-lock.json
package.json

Closes #127 
3. Run `npm ci`
4. Run `npm run generate:custom-blocks-plugin`, then `npm run generate:custom-block` to create a test block that we can check our linting rules against
5. Run `npm run lint:js` and confirm that it runs successfully (it should report an error if your `view.js` has a `console.log` statement)
6. Delete type definitions or otherwise make changes to the generated JS files that should cause linting errors
7. Confirm that `npm run lint:js` reports the expected errors

chore: use wordpress eslint plugin

---

README.md
generators/page-template.js
generators/post-type.js
generators/taxonomy.js
src/php/inc/setup-queries.php
src/php/inc/theme-scripts.php
src/php/inc/theme-setup.php

This fixes an issue where posts from custom post types were excluded from archive pages, such as by date, category, or tag, as well as the home page which lists recent posts. It requires a little bit of manual intervention from developers when they generate post types, but it's a one-liner, and instructions were updated to make it clear what to do on post type creation.
Closes #115 
4. Run `npm run generate:post-type` and answer the prompts to create a new custom post type, like "Recipes"
5. Confirm that the output of the generator includes a message about how to enable the post type on archive pages
6. Follow the instructions in the message/comments to add the post type to the …

fix: custom post type tags excluded from archive pages

---

README.md
generators/meta-box.js
package.json
src/php/functions.php

This works sets up a generator for registering meta boxes on different post types. It only covers a basic text input, leaving more advanced implementations up to developers.
Closes #133 
4. Run `npm run generate:meta-box` and answer the questions, at least enabling the meta box for default `post` posts
5. Add or edit a post, confirming that the meta box shows up in the editor with the values you specified
6. Enter some data in the field, and save your changes, confirming that no errors are thrown and that the value persists when you reload the page
7. Add other meta boxes with different values for context/positioning/post types and confirm that they work as you would expect (more or less, context and …

feat: add generator for meta boxes

---

Dockerfile

[WordPress 6.4 was recently released](https://wordpress.org/documentation/wordpress-version/version-6-4/). It doesn't appear to introduce any changes that would impact the starter template–it mostly adds new features, improvements, and a new default theme (that we don't use).
3. Stop your development process (Ctrl+C, `docker compose down`)
4. Run `docker compose build`
5. Run `npm start`
6. Confirm that the site works as expected with no breaking changes or obvious issues
7. Check the site admin and confirm that the version is shown as 6.4 and that there aren't any obvious breaking changes or issues

chore: bump WordPress version to 6.4

---

README.md

There were two links that caused issues for folks getting started with this starter template. The link to generate a new repo was broken because of its relative path not accounting for things like `/blob/main/` in the `README` URL. There was also a `localhost` link with `https` for the protocol, which caused browsers to show error messages about site security.
2. Check that the localhost links in the `README` use `http` instead of `https`
3. Click the link to generate a new repo and confirm that it leads to the page for creating a repo from the template

docs: update broken links in README
